# Generated by Django 6.0.2 on 2026-03-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_steam_avatar_user_steam_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discord_access_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='discord_avatar',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='discord_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='discord_polling_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='discord_refresh_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='discord_username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
