# Generated by Django 6.0.2 on 2026-03-07 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_discord_access_token_user_discord_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='xbox_access_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='xbox_avatar',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='xbox_gamertag',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='xbox_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='xbox_polling_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='xbox_refresh_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='xbox_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
