# Generated by Django 6.0.2 on 2026-03-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_xbox_access_token_user_xbox_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='psn_account_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='psn_avatar',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='psn_polling_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='psn_username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
