# Generated by Django 6.0.2 on 2026-03-09 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(blank=True, choices=[('playing', 'Playing'), ('completed', 'Completed'), ('dropped', 'Dropped'), ('backlog', 'Backlog')], default='playing', max_length=20),
        ),
    ]
