# Generated by Django 6.0.2 on 2026-03-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='source',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('steam', 'Steam'), ('xbox', 'Xbox'), ('discord', 'Discord')], default='manual', max_length=20),
        ),
    ]
