# Generated by Django 6.0.2 on 2026-03-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play_sessions', '0002_session_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='source',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('steam', 'Steam'), ('xbox', 'Xbox'), ('discord', 'Discord'), ('psn', 'PSN')], default='manual', max_length=20),
        ),
    ]
