# Generated by Django 6.0.2 on 2026-03-09 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play_sessions', '0003_alter_session_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='goal',
            field=models.TextField(blank=True),
        ),
    ]
